# Generated by Django 4.2.7 on 2023-11-11 16:04
import string

from django.conf import settings
from django.db import migrations

from core.constants.db import CONST_CLIENT_JOBS_REPORTS_VIEW

sql_file_path = settings.BASE_DIR / "core" / "sql" / "create_client_jobs_report_view.sql"
sql_file = open(str(sql_file_path), "r")
sql_template = string.Template(sql_file.read())
sql_code = sql_template.substitute(view_name=CONST_CLIENT_JOBS_REPORTS_VIEW)
sql_file.close()


class Migration(migrations.Migration):
    dependencies = [("client", "0001_initial"), ("job", "0001_initial")]

    operations = [
        migrations.RunSQL(sql_code, f"DROP view {CONST_CLIENT_JOBS_REPORTS_VIEW}")
    ]
