# Generated by Django 4.2.6 on 2023-10-17 10:44

import core.models.mixins.get_model_instance_as_dict
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("reports", "0001_create_client_jobs_db_view"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientJobsReportsDBView",
            fields=[
                (
                    "client_id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("client_name", models.CharField(blank=True, max_length=50, null=True)),
                ("job_completed_count", models.IntegerField(blank=True, null=True)),
                ("job_not_completed_count", models.IntegerField(blank=True, null=True)),
                ("job_past_due_count", models.IntegerField(blank=True, null=True)),
                ("job_in_progress_count", models.IntegerField(blank=True, null=True)),
                ("job_archived_count", models.IntegerField(blank=True, null=True)),
                ("job_not_started_count", models.IntegerField(blank=True, null=True)),
                ("job_draft_count", models.IntegerField(blank=True, null=True)),
                ("job_year", models.IntegerField(blank=True, null=True)),
                ("job_month", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Client jobs reports db view",
                "verbose_name_plural": "Client jobs reports db view",
                "db_table": "client_jobs_reports_view",
                "db_table_comment": "Client jobs reports db view.",
                "ordering": ["client_name"],
                "managed": False,
            },
            bases=(
                core.models.mixins.get_model_instance_as_dict.GetModelInstanceAsDictMixin,
                models.Model,
            ),
        ),
    ]
