#version: "3"
services:
  backend:
    restart: no
    container_name: beachwoodfinancial_development_webapp
    environment:
      - TERM=xterm-256color
      - COLOR_PROMPT=yes
      - LANG=C.UTF-8
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - PIP_DISABLE_PIP_VERSION_CHECK=1
      #      - PIP_NO_CACHE_DIR=off
      - NODE_ENV=development
      - PIP_PROGRESS_BAR=on
    tty: true
    stdin_open: true
    build:
      context: ./
      dockerfile: ./docker/django/Dockerfile
      #      target: development
      args:
        BUILD_ENV: development
        progress: plain
    working_dir:
      /beachwoodfinancial_development/src
      #    ports:
    #      - "8000:8000"
    expose:
      - 8000
    volumes:
#      - .:/beachwoodfinancial_development:z
      - staticfiles:/beachwoodfinancial_development/src/staticfiles
      - type: bind
        source: .
        target: /beachwoodfinancial_development:z
    env_file:
      - ./src/.env/.env_docker
    command: /start
    depends_on:
      - db
      - cache

  db:
    image: postgres:alpine
    tty: true
    stdin_open: true
    container_name: beachwoodfinancial_development_db
    #    network_mode: host
    ports:
      - "5433:5432"
    expose:
      - "5432"
    volumes:
      - pgdata:/var/lib/postgresql/data:Z
    environment:
      - TERM=xterm-256color
      - COLOR_PROMPT=yes
      - LANG=C.UTF-8
      - POSTGRES_USER=postgres
      - POSTGRES_DB=beachwoodfinancial_development
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_HOST_AUTH_METHOD=trust
  cache:
    restart: always
    container_name: beachwoodfinancial_development_cache
    tty: true
    stdin_open: true
    #    command: /bin/sh -c "redis-server --requirepass $$REDIS_HOST_PASSWORD"
    ports:
      - "6379:6379"
    image: redis:alpine
    expose:
      - 6379
    #    env_file:
    #      - ./src/.env/.redis.env
    environment:
      - TERM=xterm-256color
      - COLOR_PROMPT=yes
      - LANG=C.UTF-8

  nginx:
    image: nginx:latest
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "80:80"
    #      - "443:443"  # This is for SSL 
    volumes:
      - staticfiles:/home/static/staticfiles
      - mediafiles:/home/media/media
    depends_on:
      - backend
    environment:
      - TERM=xterm-256color
      - COLOR_PROMPT=yes
      - LANG=C.UTF-8

volumes:
  #  code_volume:
  #    driver: local
  #    driver_opts:
  #      type: none
  #      device: .
  #      o: bind,rw,z
  #    labels:
  #      selinux.label: system_u:object_r:docker_var_lib_t:s0
  pgdata:
  #  static-data:
  staticfiles:
  mediafiles:
