[project]
name = "Leadgerflare_Web_Application"
version = "1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = []

[tool.black]
line-length = 85
target-version = ['py314'] # Updated to Python 3.13
preview = true
unstable-feature = true
unstable = true
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.isort]
py_version = 313 # Updated to Python 3.13
profile = "django"
line_length = 85
force_single_line = true
use_parentheses = true
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
known_first_party = ["your_project_name"] # Replace with your project's name
known_third_party = [
    "django",
    "numpy",
    "pandas",
] # Add your third-party dependencies

[tool.djlint]
profile = "django"
extension = "html,djhtml"
indent = 4
# exclude directories and file patterns (comma separated)
exclude = ".venv,venv,.tox,build,dist,node_modules,src,src/**,**/*.py,**/__pycache__,**/migrations/**"
blank_line_after_tag = "load,extends,include"
blank_line_before_tag = "load,extends,include"
max_line_length = 95
format_attribute_template_tags = true
format_js = true
format_css = true
ignore = "H006, H014"


[tool.mypy]
python_version = "3.14"             # Updated to Python 3.13
ignore_missing_imports = true
follow_imports = "silent"
no_implicit_optional = true
strict_optional = true
warn_unused_configs = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
warn_unreachable = true
warn_return_any = false
check_untyped_defs = true
disallow_untyped_calls = false
disallow_untyped_defs = true
disallow_incomplete_defs = true
disallow_untyped_decorators = false
disallow_subclassing_any = true
exclude = ["docs", "test", "tests"]

[tool.bandit]
targets = ["."]
skips = ["B101"] # Example: Skip assert statement checks

[tool.docformatter]
wrap-summaries = 82
wrap-descriptions = 81
blank = true
pre-summary-newline = true
pre-summary-space = true
make-summary-multi-line = true
