[tool.black]
line-length = 91
target-version = ['py312']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  # The following are specific to Black, you probably don't want those.
  | blib2to3
  | tests/data
  | profiling
)/
'''

[tool.isort]
py_version = 312
profile = "django"
# known_django = "django"
line_length = 91
force_single_line = true
# known_first_party = "django_components"
use_parentheses = true
#sections = ["FUTURE", "STDLIB", "THIRDPARTY", "DJANGO", "FIRSTPARTY", "LOCALFOLDER"]
#skip = [".tox", "docs"]

[tool.djlint]
profile = "django"
extension = "html.dj"
indent = 4
exclude = ".venv,venv,.tox"
blank_line_after_tag = "load,extends,include"
blank_line_before_tag = "load,extends,include"
max_line_length = 95
format_attribute_template_tags = true
format_js = true
format_css = true
ignore = "H006"

[tool.ruff]
line-length = 91
# Skip unused variable rules (`F841`).
#ignore = ["F841", "F401", "E402", "E501", "E741", "W503"]
ignore = ["F841", "F401", "E402", "E501", "E741"]
show-fixes = true
ignore-init-module-imports = true
target-version = "py312"
indent-width = 4
# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
]

[tool.ruff.lint.isort]
#case-sensitive = true
detect-same-package = false
combine-as-imports = true

[tool.ruff.format]
quote-style = "double"
indent-style = "tab"
# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"
docstring-code-format = true
# Enable preview style formatting.
preview = true


# 4. Ignore `E402` (import violations) in all `__init__.py` files, and in select subdirectories.
[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["E402"]
"**/{tests,docs,tools}/*" = ["E402"]

[tool.ruff.lint]
# Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`)  codes by default.
# Unlike Flake8, Ruff doesn't enable pycodestyle warnings (`W`) or
# McCabe complexity (`C901`) by default.
select = ["E4", "E7", "E9", "F"]
ignore = []
# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"
# select = [
#     # pycodestyle
#     "E",
#     # Pyflakes
#     "F",
#     # pyupgrade
#     "UP",
#     # flake8-bugbear
#     "B",
#     # flake8-simplify
#     "SIM",
#     # isort
#     "I",
# ]


[tool.bandit]


[tool.mypy]
warn_return_any = true
warn_unused_configs = true
