# -*- coding: utf-8 -*-#
LIST_VIEW_PAGINATE_BY = 50
DEFAULT_FULL_DATE_TIME_FORMAT = "jS F Y H:i A"
DEFAULT_SHORT_TRUNCATED_STRING = 30
DEFAULT_MEDIUM_TRUNCATED_STRING = 50
DEFAULT_LONG_TRUNCATED_STRING = 70
DEFAULT_TEMPLATE_TABLE_LIST_TRUNCATED_STRING = 40
DEFAULT_TEMPLATE_TABLE_LIST_LONG_TRUNCATED_STRING = 200
DEFAULT_DB_STRING_COL_LENGTH = 90
IS_SHOW_CREATED_AT = False
