# -*- coding: utf-8 -*-#
CON_NOT_STARTED = "not_started"
CON_IN_PROGRESS = "in_progress"
CON_PAST_DUE = "past_due"
CON_COMPLETED = "completed"
CON_NOT_COMPLETED = "not_completed"
CON_ARCHIVED = "archived"
CON_REJECTED = "rejected"
CON_ENABLED = "enabled"
CON_DISABLED = "disabled"
CON_PENDING = "pending"
CON_CANCELED = "canceled"
CON_DRAFT = "draft"
ONGOING = "ongoing"
STALLED = "stalled"
NEED_INFO = "need info"
