#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


#python3 manage.py makemigrations
#python3 manage.py migrate
##exec python3 manage.py runserver 0.0.0.0:8000
#python3 manage.py runserver 0.0.0.0:8000
# setup frontend
echo "###############################################################"
echo "Waiting for frontend to setup..."
cd frontend
npm set progress true
pnpm install
pnpm run build
echo "###############################################################"

echo "###############################################################"
echo "Waiting for enter src folder ..."
cd ..
echo "###############################################################"

echo "###############################################################"
echo "Waiting for db to be migrated..."

python3 manage.py makemigrations -v 1

python3 manage.py migrate -v 1

echo "Waiting for reports migration to be ready..."
touch ./reports/migrations/__init__.py
python3 manage.py migrate reports 0001_create_client_jobs_db_view -v 1
python3 manage.py migrate -v 1

echo "Waiting for create users groups..."
python3 manage.py create_groups

echo "Create createsuperuser"
#python3 manage.py createsuperuser -v 1 --noinput
python3 manage.py beachwood_create_superuser -v 1


echo "###############################################################"

echo "###############################################################"
echo "Executing custom commands ..."
echo "Waiting for init and setup django site..."
python3 manage.py set_site -i


echo "Waiting for init beachwood site settings..."
python3 manage.py init_site_settings -i -v 2 -e


echo "Waiting for init beachwood cache data..."
python3 manage.py init_cache_data -i -e



echo "###############################################################"


echo "###############################################################"
echo "Waiting for collect static..."
python3 manage.py collectstatic --noinput
echo "###############################################################"
# python3 manage.py createsuperuser --noinput

#gunicorn backend.wsgi --bind 0.0.0.0:8000 --workers 4 --threads 4

# for debug
echo "###############################################################"
echo "Waiting for runserver..."
#python3 manage.py runserver 0.0.0.0:8000
gunicorn --config gunicorn.conf.py
echo "###############################################################"
